name: John Finley's Online Portfolio
permalink: none
markdown: redcarpet
highlighter: pygments
include: ['.htaccess']
exclude: [
  'assets/css/src',
  'assets/css/build',
  'assets/img/source',
  'assets/javascript/src',
  'assets/javascript/build',
  'node_modules',
  'Gruntfile.js',
  'package.json',
  'Gem*'
]
